conky.config = {
    alignment = 'top_right',
    background = true,
    cpu_avg_samples = 2,
    default_color = '#FFFFFF',
    double_buffer = true,
    font = 'Inter:size=38:weight=Light',
    gap_x = 40,
    gap_y = 60,
    
    -- Native desktop window configuration for accurate spatial mapping
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    
    update_interval = 1.0,
    use_xft = true,
    xftalpha = 1,
    override_utf8_locale = true,
}

conky.text = [[
${alignr}${time %H:%M:%S}
${alignr}${font Inter:size=12:weight=Regular}${color lightgray}${time %A, %d %B %Y}${font}${color}
]]