conky.config = {
    alignment = 'top_right',
    background = true,
    cpu_avg_samples = 2,
    default_color = '#FFFFFF',
    double_buffer = true,
    font = 'Inter:size=38:weight=Light',
    gap_x = 40,
    gap_y = 60,
    
    minimum_width = 320,
    minimum_height = 110, -- Reduced from 140 to cut off the bottom gap
    maximum_width = 320,
    
    -- CAIRO DRAWING INTEGRATION
    lua_load = '~/.config/conky/background.lua',
    lua_draw_hook_pre = 'draw_bg',
    
    -- WINDOW COMPOSITION
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    
    border_inner_margin = 18,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    
    update_interval = 1.0,
    use_xft = true,
    xftalpha = 1,
    override_utf8_locale = true,
}

conky.text = [[
${alignc}${time %H:%M:%S}
${voffset 4}${alignc}${font Inter:size=11:weight=Regular}${color #CCCCCC}${time %A, %d %B %Y}${font}${color}
]]